kolla_base_distro: "ubuntu"
kolla_install_type: "binary"
# openstack_release: "victoria"
openstack_release: "wallaby"
# Valid options are [ qemu, kvm, vmware ]
nova_compute_virt_type: "qemu"

##############################
# Neutron - Networking Options
##############################
# This interface is what all your api services will be bound to by default.
# Additionally, all vxlan/tunnel and storage network traffic will go over this
# interface by default. This interface must contain an IP address.
# It is possible for hosts to have non-matching names of interfaces - these can
# be set in an inventory file per host or per group or stored separately, see
#     http://docs.ansible.com/ansible/intro_inventory.html
# Yet another way to workaround the naming problem is to create a bond for the
# interface on all hosts and give the bond name here. Similar strategy can be
# followed for other types of interfaces.
#network_interface: "eth0"
network_interface: "ens3"

# This is the raw interface given to neutron as its external network port. Even
# though an IP address can exist on this interface, it will be unusable in most
# configurations. It is recommended this interface not be configured with any IP
# addresses for that reason.
neutron_external_interface: "ens4"


# enable_haproxy: "no"
# enable_keepalived: "no"
#enable_haproxy: "yes"
enable_haproxy: "yes"
enable_keepalived: "yes"
# This should be a VIP, an unused IP on your network that will float between
# the hosts running keepalived for high-availability. If you want to run an
# All-In-One without haproxy and keepalived, you can set enable_haproxy to no
# in "OpenStack options" section, and set this value to the IP of your
# 'network_interface' as set in the Networking section below.
kolla_internal_vip_address: "192.168.122.240"


# Using harbor secure registry with project name(project name ~ namespace)
# docker_registry: 'harbor.k8s.maxrinal.test'
# docker_namespace: 'cachedhub/kolla'

# Using insecure registry(simple docker pull trough cache)
docker_registry: 192.168.122.1:4000
# Test docker_regsitry reachable 
# curl 192.168.122.1:4000/v2/_catalog
docker_registry_insecure: yes
docker_namespace: "kolla"



enable_horizon: yes

# openstack_logging_debug: yes
openstack_logging_debug: no


enable_designate: "yes"
enable_barbican: "yes"


# enable_horizon_karbor: yes
# enable_murano: yes
# enable_horizon_magnum: "yes"
# enable_trove: "yes"
enable_fluentd: "no"